import Head from 'next/head'
import Header from '../components/Header'
import Banner from '../components/Banner'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import SmallCard from '../components/SmallCard'
import MediumCard from '../components/MediumCard'
import Footer from '../components/Footer'
import MFooter from '../components/MFooter'

export default function Home({ exploreData, cardsData }) {
  return (
    <div className="">
      <Head>
        <title>likidi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*the header  */}
      <Header />
      {/*the banner  */}
      <Banner />
      {/*the banner  */}
      {/*the main section   */}

      <main className="max-w-7xl mx-10 md:px-16 sm:px-10">
        <section className="pt-6 ">
          <h2 className="text-4xl font-semibold pb-5 ">Some informations</h2>
          {/*aficher qlq information   */}

          <div className="grid grid-cols-1 mx-10 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 ">
            {exploreData?.map(({ img, distance, location }) => (
              <SmallCard
                key={img}
                img={img}
                distance={distance}
                location={location}
              />
            ))}
          </div>
        </section>

        <section>
          <h2 className=" text-4xl font-semibold py-8">live anywere</h2>
          <div className="flex space-x-3 overflow-scroll">
            {cardsData?.map((item) => (
              <MediumCard key={item.img} img={item.img} title={item.title} />
            ))}
          </div>
        </section>
      </main>
      <Footer />
      <MFooter />
    </div>
  )
}
export async function getStaticProps() {
  {
    /*passer le lins de fichier des  information des produit ici dans le fetch */
  }
  const exploreData = await fetch('https://links.papareact.com/pyp').then(
    (res) => res.json()
  )

  const cardsData = await fetch('https://links.papareact.com/zp1').then((res) =>
    res.json()
  )

  return {
    props: {
      exploreData,
      cardsData,
    },
  }
}
