import Head from 'next/head'
import Header from '../components/Header'
import Banner from '../components/Banner'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>likidi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*the header  */}
      <Header />
      {/*the banner  */}
      <Banner />
    </div>
  )
}
